# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh

build-latex:
    stage: build
    image: registry.gitlab.com/islandoftex/images/texlive:latest
    before_script:
     - cd latex

    script:
     - pdflatex thesis.tex
     - biber thesis
     - pdflatex thesis.tex
    after_script:
     - cat thesis.log
    artifacts:
     paths:
      - thesis.pdf


build:
    stage: build
    image: gcc
    before_script:
     - git submodule sync --recursive
     - git submodule update --init --recursive
     - apt-get update --yes
     - apt-get install --yes cmake build-essential gdb pkg-config curl zip unzip tar
     - ls vcpkg
     - echo "calling vcpkg"
     - sh ./vcpkg/bootstrap-vcpkg.sh
     - ./vcpkg/vcpkg install gsl 
     - ./vcpkg/vcpkg integrate install

    script:
     - mkdir build
     - cd build
     - cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake ..
     - make
    artifacts:
      paths:
       - build
  