# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh

build-latex:
    stage: build
    image: registry.gitlab.com/islandoftex/images/texlive:latest

    script:
     - cd latex
     - pdflatex thesis.tex
     - bibtex thesis
     - pdflatex thesis.tex
     #- biber literatur.bib
    # - pdflatex thesis.tex
    #after_script:
    # - cat latex/thesis.log
    artifacts:
     paths:
      - latex/thesis.pdf


build:
    stage: build
    image: gcc
    before_script:
     - git submodule sync --recursive
     - git submodule update --init --recursive
     - apt-get update --yes
     - apt-get install --yes cmake libarmadillo-dev libopenblas-dev liblapack-dev

    script:
     - mkdir build
     - cd build
     - cmake ..
     - make
    artifacts:
      paths:
       - build
  

test:
    stage: test
    image: gcc
    before_script:
     - git submodule sync --recursive
     - git submodule update --init --recursive
     - apt-get update --yes
     - apt-get install --yes cmake libarmadillo-dev libopenblas-dev liblapack-dev
    script:
     - mkdir build_test
     - cd build_test
     - cmake --build .. --target test
     - make